# Generated by Django 2.2.7 on 2020-01-28 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micromarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=8, verbose_name='Referência do chamado')),
                ('summary', models.TextField(verbose_name='Descrição')),
                ('debug', models.TextField(blank=True, verbose_name='Ações tomadas no micromarket')),
                ('level', models.CharField(choices=[('WC', 'Alerta de conexão'), ('VP', 'Produto vencido'), ('PP', 'Erro no pagamento')], max_length=2, verbose_name='Nível')),
                ('isChecked', models.BooleanField(default=False, verbose_name='Visualizado')),
                ('ddmmyyy_created', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('instalation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='micromarket.Instalation', verbose_name='Serviço de Autopagamento')),
            ],
            options={
                'verbose_name': 'Inspetor',
                'verbose_name_plural': 'Inspetores',
            },
        ),
    ]
