# Generated by Django 2.2.7 on 2020-01-28 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('state', models.CharField(max_length=80, verbose_name='Estado')),
                ('city', models.CharField(max_length=120, verbose_name='Cidade')),
                ('district', models.CharField(max_length=80, verbose_name='Bairro')),
                ('additionalInformation', models.CharField(max_length=80, verbose_name='Complemento')),
                ('streetSuffix', models.CharField(max_length=15, verbose_name='Sufixo')),
                ('street', models.CharField(max_length=120, verbose_name='Rua')),
                ('number', models.CharField(max_length=8, verbose_name='Número')),
                ('postalCode', models.CharField(max_length=9, verbose_name='Código Postal')),
                ('country', models.CharField(max_length=25, verbose_name='País')),
                ('countryBacenCode', models.CharField(max_length=4, verbose_name='Código Bacen do País')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Serviços de Autopagamento',
            },
        ),
        migrations.CreateModel(
            name='Instalation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=120, verbose_name='Responsável pela instalação')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail para contato')),
                ('identifier', models.CharField(max_length=32, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='micromarket.Address', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Instalação',
                'verbose_name_plural': 'Instalações',
            },
        ),
    ]
